# 快速重新部署lxd，用于lxd配置测试
- name: Clean compute node
  hosts: compute_node
  tasks:
    # 清理lxd
    - include_tasks: tasks/clean_lxd.yml
- name: Clean management node
  hosts: management_node
  tasks:
    # 清理云平台数据
    - include_tasks: tasks/clean_cloud.yml
    # 清理lxd
    - include_tasks: tasks/clean_lxd.yml
- name: Init management node
  hosts: management_node
  tasks:
    # 管理节点需要安装lxd
    - include_tasks: tasks/install_lxd.yml
    # 初始化管理节点
    - include_tasks: tasks/init_management_node.yml
- name: Init compute node
  hosts: compute_node
  tasks:
    # 计算节点需要安装lxd和ovs
    - include_tasks: tasks/install_lxd.yml
    # 初始化计算节点
    - include_tasks: tasks/init_compute_node.yml
- name: Init cloud
  hosts: management_node
  tasks:
    # 初始化LXD
    - include_tasks: tasks/init_lxd.yml
    # 初始化数据库和机器
    - include_tasks: tasks/init_cloud.yml
