# 判断机器是否已经加入集群
- name: Check if already in cluster
  become: true
  become_user: root
  become_method: sudo
  changed_when: false
  register: lxc_cluster
  ignore_errors: true
  ansible.builtin.command:
    cmd: lxc cluster list
# 复制lxd初始化配置
- name: Copy LXD config
  # when: "lxc_cluster.rc != 0"
  ansible.builtin.template:
    src: configs/lxd_init.yml
    dest: /home/{{ ansible_user }}/lxd_init.yml
    mode: 0644
    owner: "{{ ansible_user }}"
# 导入lxd初始化配置
- name: Import LXD init config
  become: true
  become_user: root
  become_method: sudo
  changed_when: false
  # when: "lxc_cluster.rc != 0"
  ansible.builtin.shell:
    cmd: lxd init --preseed < /home/{{ ansible_user }}/lxd_init.yml
# 获取证书
- name: Get LXD cluster cert
  become: true
  become_user: root
  become_method: sudo
  changed_when: false
  register: cluster_cert
  ansible.builtin.shell:
    cmd: sed ':a;N;$!ba;s/\n/\n\n/g' /var/snap/lxd/common/lxd/cluster.crt
# 保存证书变量
- name: Save cluster cert into ansible fact
  ansible.builtin.set_fact:
    cluster_cert: "{{ cluster_cert.stdout }}"