# 初始化ssh私钥
- name: Create SSH key
  changed_when: false
  ansible.builtin.shell:
    cmd: if [ ! -f /home/{{ ansible_user }}/.ssh/id_rsa ]; then ssh-keygen -f /home/{{ ansible_user }}/.ssh/id_rsa -P ''; fi
# 获取ssh公钥
- name: Get SSH pub key
  changed_when: false
  register: ssh_pub_key
  ansible.builtin.command:
    cmd: cat /home/{{ ansible_user }}/.ssh/id_rsa.pub
# 保存ssh公钥
- name: Save SSH pub key into ansible fact
  ansible.builtin.set_fact:
    ssh_pub_key: "{{ ssh_pub_key.stdout }}"