# 安装python环境和依赖
- name: Install python3-pip
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - python3-dev
- name: Install pip requirments
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.pip:
    executable: pip3
    extra_args: -i https://pypi.doubanio.com/simple
    name:
      - flask
      - flask-sqlalchemy
      - flask-sock
      - IPy
      - psutil
# 测试所有服务器的连接并加载ssh指纹
- name: Test ssh connection
  changed_when: false
  with_items:
    - "{{groups.management_node}}"
    - "{{groups.special_node}}"
    - "{{groups.compute_node}}"
    - "{{groups.network_node}}"
  ansible.builtin.shell:
    cmd: ssh {{ item }} -o 'StrictHostKeychecking=no' hostname
# 复制项目代码 (copy is too slow, use synchronize instead)
- name: Copy code
  ansible.builtin.synchronize:
    src: ../../miniCloud
    dest: /home/{{ ansible_user }}/
    rsync_opts:
      - "--exclude=ansible_scripts"
# 复制项目配置
- name: Copy config
  ansible.builtin.template:
    src: configs/config.py
    dest: /home/{{ ansible_user }}/miniCloud/config.py
    mode: 0644
    owner: "{{ ansible_user }}"
# 执行初始化
- name: Init cloud
  changed_when: false
  register: result
  ansible.builtin.command:
    cmd: python3 init_cloud.py
    chdir: /home/{{ ansible_user }}/miniCloud
# 查看初始化输出
- name: Show init result
  debug: var=result verbosity=0
