# 添加远程集群
- name: Add remote cluster
  become: true
  become_user: root
  become_method: sudo
  changed_when: false
  ignore_errors: true
  ansible.builtin.command:
    cmd: lxc remote add miniCloud {{ groups['compute_master_node'][0] }} --accept-certificate --password {{ cluster_password }} && lxc remote switch miniCloud
# 检查存储池是否已创建
- name: Check if storage pool exists
  become: true
  become_user: root
  become_method: sudo
  changed_when: false
  register: has_storage_pool
  ignore_errors: true
  ansible.builtin.command:
    cmd: lxc storage show miniCloud
# 创建lxd存储池
- name: Create storage pool
  become: true
  become_user: root
  become_method: sudo
  changed_when: false
  when: "has_storage_pool.rc != 0"
  with_items: "{{groups.compute_node}}"
  ansible.builtin.shell:
    cmd: lxc storage create miniCloud btrfs source={{storage_pool_path}} --target {{item}}
# 启用lxd存储池
- name: Start storage pool
  become: true
  become_user: root
  become_method: sudo
  changed_when: false
  ansible.builtin.shell:
    cmd: lxc storage create miniCloud btrfs
# 导入清华镜像
- name: Import LXD mirror
  become: true
  become_user: root
  become_method: sudo
  changed_when: false
  ansible.builtin.shell:
    cmd: lxc remote list | grep 'tuna-images' || lxc remote add tuna-images https://mirrors.tuna.tsinghua.edu.cn/lxc-images/ --protocol=simplestreams --public
